name: i_streamo_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  local_auth: ^2.1.2
  equatable: ^2.0.0
  http: ^0.13.5
  get_storage: ^2.0.3
  fluttertoast: ^8.0.9
  scrollable_positioned_list: ^0.3.5
  flutter: 
    sdk: flutter
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  connectivity_plus: ^2.3.9

dev_dependencies: 
  flutter_launcher_icons: "^0.10.0"
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/github.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48

flutter: 
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: asset/Merriweather/Merriweather-Regular.ttf
        - asset: asset/Merriweather/Merriweather-Italic.ttf
        - asset: asset/Merriweather/Merriweather-Black.ttf
        - asset: asset/Merriweather/Merriweather-Bold.ttf
        - asset: asset/Merriweather/Merriweather-Light.ttf
  assets:
    - asset/github.png
    - asset/

